### ISSUE TITLE
Can not find moule ../ember-migrator

### ISSUE THREAD

**Issue by gonvaled** [fivetanley/ember-cli-migrator#30]
```
» node_modules/ember-cli-migrator/bin/ember-cli-migrator

module.js:340
    throw err;
          ^
Error: Cannot find module '../ember-migrator'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (XXX/node_modules/ember-cli-migrator/bin/ember-cli-migrator:8:21)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

should be:

```
var EmberMigrator = require('../lib/ember-migrator');
```

**Comment by fivetanley** [comment]
Good catch! Fixed in 208fa5cc77f2caf7d7dff83f2246ca398370194a and 0.2.1 on npm.
