### ISSUE TITLE
Add reporting about module being refactored

### ISSUE THREAD

**Issue by gonvaled** [fivetanley/ember-cli-migrator#31]
I get the following error:

```
require("recast").Visitor deprecated Please use require("recast").visit instead of require("recast").Visitor node_modules/ember-cli-migrator/lib/ember-migrator.js:42:31
require("recast").Visitor deprecated Please use require("recast").visit instead of require("recast").Visitor node_modules/ember-cli-migrator/node_modules/recast/node_modules/cls/main.js:91:71
preprocess

Error: Line 1: Unexpected token ILLEGAL
    at throwError (/home/gonvaled-data/projects/frontend-app/node_modules/ember-cli-migrator/node_modules/recast/node_modules/esprima-fb/esprima.js:2422:21)
    at scanPunctuator (/home/gonvaled-data/projects/frontend-app/node_modules/ember-cli-migrator/node_modules/recast/node_modules/esprima-fb/esprima.js:849:9)
    at advance (/home/gonvaled-data/projects/frontend-app/node_modules/ember-cli-migrator/node_modules/recast/node_modules/esprima-fb/esprima.js:1541:16)
    at peek (/home/gonvaled-data/projects/frontend-app/node_modules/ember-cli-migrator/node_modules/recast/node_modules/esprima-fb/esprima.js:1567:21)
    at parseProgram (/home/gonvaled-data/projects/frontend-app/node_modules/ember-cli-migrator/node_modules/recast/node_modules/esprima-fb/esprima.js:5543:9)
    at Object.parse (/home/gonvaled-data/projects/frontend-app/node_modules/ember-cli-migrator/node_modules/recast/node_modules/esprima-fb/esprima.js:6706:23)
    at Object.parse (/home/gonvaled-data/projects/frontend-app/node_modules/ember-cli-migrator/node_modules/recast/lib/parser.js:25:32)
    at EmberMigrator.splitFile (/home/gonvaled-data/projects/frontend-app/node_modules/ember-cli-migrator/lib/ember-migrator.js:159:20)
    at Array.forEach (native)
    at EmberMigrator_run [as run] (/home/gonvaled-data/projects/frontend-app/node_modules/ember-cli-migrator/lib/ember-migrator.js:121:11)
```

But I have not enough context to know what is going on. Where does it fail? Which file? Which line? Which token?

Is it possible to have a command-line flag to increase logging?

**Comment by kiwiupover** [comment]
@gonvaled What was the command you ran and for that matter what is the structure of your app? What folder is your ember app located in? Where are you trying to move it to?

**Comment by estoner** [comment]
I just ran into this also.  In my case, the problem was that I was running the migrator against the root directory of my app, so it was parsing everything in bower_components, and something in there had a character it didn't like.

The PR I just submitted added logging to help debug this.
