### ISSUE TITLE
.gitkeep files

### ISSUE THREAD

**Issue by kiwiupover** [fivetanley/ember-cli-migrator#42]
Should `.gitkeep` files crash the process? Also on a mac `.DS.Store` would also crash the process.

When I used the migrator on the past I thought it ignored `.dotfiles` was I mistaken.

```sh 
No Change or Move javascripts/components/.gitkeep

/usr/local/lib/node_modules/ember-cli-migrator/node_modules/exec-sync/bin/index.js:68
        throw new Error(error);
              ^
Error: fatal: renaming 'javascripts/components/.gitkeep' failed: No such file or directory
    at module.exports (/usr/local/lib/node_modules/ember-cli-migrator/node_modules/exec-sync/bin/index.js:68:15)
    at null.<anonymous> (/usr/local/lib/node_modules/ember-cli-migrator/lib/ember-migrator.js:131:9)
    at Array.forEach (native)
    at EmberMigrator_run [as run] (/usr/local/lib/node_modules/ember-cli-migrator/lib/ember-migrator.js:123:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/ember-cli-migrator/bin/ember-cli-migrator:30:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Cheers

**Comment by fivetanley** [comment]
Definitely seems like a bug. Might seem best to just not bother with them.

**Comment by kiwiupover** [comment]
You can run `find javascripts -name '.gitkeep' -delete` with `javascripts` being the folder with holding the ember app before using the migrator.
