### ISSUE TITLE
Yeoman ember generator migrate with ember-cli-migrator error

### ISSUE THREAD

**Issue by hoetmaaiers** [fivetanley/ember-cli-migrator#57]
The migration starts off good, but after multiple `Copying Unknown File ` I get the folowing error:
```
usr/local/lib/node_modules/ember-cli-migrator/lib/migrator-visitor.js:81       
   var __namespace__ = leftNode.object.object && leftNode.object.object.nam
                                          ^ 
TypeError: Cannot read property 'object' of undefined
     at Context.MigratorVisitorPrototype.visitAssignmentExpression (/usr/local/lib/node_modules/ember-cli-migrator/lib/migrator-visitor.js:81:42)
     at Context.invokeVisitorMethod (/usr/local/lib/node_modules/ember-cli-migrator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:306:43)
     at Visitor.PVp.visitWithoutReset (/usr/local/lib/node_modules/ember-cli-migrator/node_modules/recast/node_modules/ast-types/lib/path-visitor.js:180:28)
```

**Comment by hoetmaaiers** [comment]
Ok, I should have read this issue first: https://github.com/fivetanley/ember-cli-migrator/issues/56
