### ISSUE TITLE
why git is necessary to migrate? I use svn.

### ISSUE THREAD

**Issue by dengshaodong** [fivetanley/ember-cli-migrator#62]
When run ember-cli-migrator in a environment without git installed, it will just fail.

D:\work\client\kiford-front\app>ember-cli-migrator
Preprocessing files
Git Move Moving adapter.js to tmp\app\adapter.js
fatal: Not a git repository (or any of the parent directories): .git
child_process.js:1389
    throw err;
          ^
Error: Command failed: git mv adapter.js tmp\app\adapter.js
fatal: Not a git repository (or any of the parent directories): .git

    at checkExecSyncError (child_process.js:1346:13)
    at execSync (child_process.js:1386:13)
    at null.<anonymous> (C:\Users\dengshaodong\AppData\Roaming\npm\node_modules\
ember-cli-migrator\lib\ember-migrator.js:93:9)
    at Array.forEach (native)
    at EmberMigrator_run [as run] (C:\Users\dengshaodong\AppData\Roaming\npm\nod
e_modules\ember-cli-migrator\lib\ember-migrator.js:84:32)
    at Object.<anonymous> (C:\Users\dengshaodong\AppData\Roaming\npm\node_module
s\ember-cli-migrator\bin\ember-cli-migrator:30:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by fivetanley** [comment]
Seems like we should have the ability to disable git.

**Comment by KedneckInc** [comment]
It would be a very good option to add.  I'm just trying the migrator out on a dummy Yeoman project that isn't in git.  While I could add the project to git, that's a bit of a pain, because I'll need to completely eradicate it afterward.
